/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ml_loan;

import weka.classifiers.Classifier;

/**
 *
 * @author Student
 */
public class LoanAppplication extends javax.swing.JFrame {

    Classification_Logistics_Loan loanObj;

    /**
     * Creates new form LoanAppplication
     */
    public LoanAppplication() {
        loanObj = new Classification_Logistics_Loan();
        loanObj.setPredictFilename("creditRisk_predict.arff");
        initComponents();
        

    }

    public void setClassifier(Classifier classifier) {
        loanObj.setClassifier(classifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        education = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dependents = new javax.swing.JComboBox<>();
        married = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        selfemployeed = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        applicantIncome = new javax.swing.JTextField();
        coapplicantIncome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loanamount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        loanamountterm = new javax.swing.JTextField();
        propety = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        evaluation = new javax.swing.JButton();
        result = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Married");

        education.setText("Yes, graduate");
        education.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationActionPerformed(evt);
            }
        });

        jLabel2.setText("Dependents");

        jLabel3.setText("Education");

        dependents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3+" }));

        married.setText("Yes, applicant is married");

        jLabel4.setText("Self-employeed");

        selfemployeed.setText("self-employeed");
        selfemployeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfemployeedActionPerformed(evt);
            }
        });

        jLabel5.setText("ApplicantIncome");

        applicantIncome.setText("0");
        applicantIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantIncomeActionPerformed(evt);
            }
        });

        coapplicantIncome.setText("0");
        coapplicantIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coapplicantIncomeActionPerformed(evt);
            }
        });

        jLabel6.setText("CoapplicantIncome");

        loanamount.setText("0");
        loanamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanamountActionPerformed(evt);
            }
        });

        jLabel7.setText("LoanAmount");

        jLabel8.setText("Loan Amount Term");

        loanamountterm.setText("0");
        loanamountterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanamounttermActionPerformed(evt);
            }
        });

        propety.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rural", "Urban", "Semiurban" }));

        jLabel9.setText("Property Area");

        evaluation.setText("click for evaluation");
        evaluation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evaluationMouseClicked(evt);
            }
        });
        evaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(evaluation)
                        .addGap(18, 18, 18)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(39, 39, 39))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selfemployeed)
                                    .addComponent(dependents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(education)
                                    .addComponent(married)
                                    .addComponent(applicantIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coapplicantIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loanamount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(propety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loanamountterm, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(156, 156, 156)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(married))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dependents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(education))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(selfemployeed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(applicantIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(coapplicantIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(loanamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(loanamountterm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(propety, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evaluation)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void educationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationActionPerformed

    private void selfemployeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfemployeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selfemployeedActionPerformed

    private void applicantIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicantIncomeActionPerformed

    private void coapplicantIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coapplicantIncomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coapplicantIncomeActionPerformed

    private void loanamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanamountActionPerformed

    private void loanamounttermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanamounttermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loanamounttermActionPerformed

    private void evaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_evaluationActionPerformed

    private void evaluationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evaluationMouseClicked
        // TODO add your handling code here:
        String marriedValue = married.isSelected() ? "Yes" : "No";
        int dep = dependents.getSelectedIndex();
        String dependentsValue = dep == 3 ? "3+" : dep + "";
        String educationValue = education.isSelected() ? "Graduate" : "NotGraduateNo";
        String selfemployeedValue = selfemployeed.isSelected() ? "Yes" : "No";
        double appIncomeValue = Double.parseDouble(applicantIncome.getText());
        double coaappIncomeValue = Double.parseDouble(coapplicantIncome.getText());
        double loanamountValue = Double.parseDouble(loanamount.getText());
        double loanamounttermValue = Double.parseDouble(loanamountterm.getText());
        int Property = propety.getSelectedIndex();
        String PropertyValue = Property == 0 ? "Rural" : Property == 1 ? "Urban" : "Semiurban";
        String resultValue = loanObj.preDictOneInstance(marriedValue, dependentsValue, educationValue, selfemployeedValue, appIncomeValue, coaappIncomeValue, loanamountValue, loanamounttermValue, PropertyValue);
        System.out.println("resultValue--> "+resultValue);
        result.setText(resultValue);
    }//GEN-LAST:event_evaluationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAppplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAppplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAppplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAppplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAppplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField applicantIncome;
    private javax.swing.JTextField coapplicantIncome;
    private javax.swing.JComboBox<String> dependents;
    private javax.swing.JCheckBox education;
    private javax.swing.JButton evaluation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField loanamount;
    private javax.swing.JTextField loanamountterm;
    private javax.swing.JCheckBox married;
    private javax.swing.JComboBox<String> propety;
    private javax.swing.JTextField result;
    private javax.swing.JCheckBox selfemployeed;
    // End of variables declaration//GEN-END:variables
}
